---
title: "Asesinatos cometidos en Costa Rica en 2023"
author: "Gabriela Rodríguez"
date: 2024-05-02
lang: es
format: html
toc: true
theme: cerulean
editor: visual
---

# Presentación
Este documento contiene un conjunto de gráficos sobre homicidios cometidos en Costa Rica e 2023

# Lectura de datos

```{r}
#| label: lectura-datos

delitos_2023 <- read.csv(file = "estadisticaspoliciales2023.csv")
```

# Filtrado de homicidios

```{r}
#| label: filtrado-homicidios

homicidios2023 <-
  delitos_2023[delitos_2023$Delito == "HOMICIDIO",]
```

# Homicidios por provincia

```{r}
#| label: homicidios_x_provincia

# Conteo de homicidios por provincia
homicidios_x_provincia <- table(homicidios2023$Provincia)

# Ordenamiento por cantidad de homicidios
homicidios_x_provincia <- sort(homicidios_x_provincia, decreasing = TRUE)

# Gráfico de barras
barplot(height = homicidios_x_provincia,
        las = 2,
        col = "purple",
        cex.names = 0.8,
        main = "Homicidios por provincia"
        )

```

# Homicidios por cantón

```{r}
#| label: homicidios_x_canton

# Conteo de homicidios por canton
homicidios_x_canton <- table(homicidios2023$Canton)

# Ordenamiento por cantidad de homicidios
homicidios_x_canton <- sort(homicidios_x_canton, decreasing = TRUE)

# Selección de los 20 cantones con más homicidios
homicidios_x_canton <- head(homicidios_x_canton, 20)

# Gráfico de barras
barplot(height = homicidios_x_canton,
        las = 2,
        col = "pink",
        cex.names = 0.6,
        main = "Homicidios por cantón"
        )
```



# Homicidios por género

```{r}
#| label: homicidios_x_género

# Conteo de homicidios por género
homicidios_x_genero <- table(homicidios2023$Genero)

# Ordenamiento por cantidad de homicidios
homicidios_x_genero <- sort(homicidios_x_genero, decreasing = TRUE)

# Gráfico de barras
barplot(height = homicidios_x_genero,
        las = 2,
        col = "grey",
        cex.names = 0.6,
        main = "Homicidios por género"
        )

```


